# Generated by Django 5.1.3 on 2024-12-31 12:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geodjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_border',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=6677),
        ),
        migrations.AlterField(
            model_name='stations',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
