# Generated by Django 5.1.3 on 2024-12-31 12:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geodjango', '0002_alter_city_border_geom_alter_stations_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_border',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=6677),
        ),
        migrations.AlterField(
            model_name='stations',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
