services:
  api:
    build: .
    #    command: gunicorn --bind :8000 --workers 2 core.wsgi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      POSTGRES_HOST: postgis
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./postgis:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h postgis -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s
