services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgis:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h postgis -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s

volumes:
  postgis:
