# fly.toml app configuration file generated for my-django on 2025-01-03T10:43:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-django'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[deploy]
  #release_command = 'python manage.py migrate'

[env]
  PORT = '8000'
  TZ = 'Asia/Tokyo'


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
  source = "my_volume"
  destination = "/mnt/images"
