# Generated by Django 5.1.4 on 2025-01-14 14:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('name_kana', models.CharField(max_length=254, null=True)),
                ('name_gener', models.CharField(max_length=254, null=True)),
                ('name_en', models.CharField(max_length=254, null=True)),
                ('category', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('place_name', models.CharField(max_length=254, null=True)),
                ('address', models.CharField(max_length=254)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('url', models.CharField(max_length=254, null=True)),
                ('note', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254, null=True)),
                ('note', models.CharField(max_length=254, null=True)),
                ('cultural_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open3d_map.culturalproperty')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
    ]
