# Generated by Django 5.1.3 on 2025-01-04 04:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalProperty',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('name_kana', models.CharField(max_length=254)),
                ('name_gener', models.CharField(max_length=254)),
                ('name_en', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('place_name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('url', models.CharField(max_length=254)),
                ('note', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
        ),
    ]
