# Generated by Django 5.1.3 on 2025-01-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalproperty',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_en',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_gener',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_kana',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='note',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='place_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='url',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
