# Generated by Django 5.1.4 on 2025-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cultural_property',
        ),
        migrations.AddField(
            model_name='culturalproperty',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='cultural_properties', to='open3d_map.movie'),
        ),
    ]
