# Generated by Django 5.1.4 on 2025-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0002_remove_movie_cultural_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_gener',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='place_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
