# Generated by Django 5.1.3 on 2025-01-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0002_alter_culturalproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalproperty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
