# Generated by Django 5.1.4 on 2025-01-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0003_alter_culturalproperty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254, null=True)),
                ('note', models.CharField(max_length=254, null=True)),
                ('cultural_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open3d_map.culturalproperty')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
    ]
