# Generated by Django 5.1.4 on 2025-01-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0003_alter_culturalproperty_name_gener_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalproperty',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='cultural_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='open3d_map.culturalproperty'),
        ),
    ]
