# Generated by Django 5.1.4 on 2025-01-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0004_remove_culturalproperty_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalproperty',
            name='note',
            field=models.CharField(max_length=4094, null=True),
        ),
    ]
