# Generated by Django 5.1.4 on 2025-01-17 05:02

import django.db.models.deletion
import open3d_map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0005_alter_culturalproperty_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=open3d_map.models.upload_to)),
                ('cultural_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='open3d_map.culturalproperty')),
            ],
        ),
    ]
