# Generated by Django 5.1.4 on 2025-01-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0006_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cultural_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='open3d_map.culturalproperty'),
        ),
    ]
