# Generated by Django 5.1.4 on 2025-03-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0008_alter_culturalproperty_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='culturalproperty',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cultural_properties', to='open3d_map.tag'),
        ),
    ]
