# Generated by Django 5.1.4 on 2025-03-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open3d_map', '0009_tag_culturalproperty_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalproperty',
            name='note',
            field=models.CharField(blank=True, max_length=4094, null=True),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
