# Generated by Django 5.1.4 on 2025-10-24 02:32

import cp_api.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('name_kana', models.CharField(max_length=254, null=True)),
                ('name_gener', models.CharField(blank=True, max_length=254, null=True)),
                ('name_en', models.CharField(max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(max_length=254)),
                ('place_name', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=254)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('url', models.CharField(blank=True, max_length=254, null=True)),
                ('note', models.CharField(blank=True, max_length=4094, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cp_api.models.upload_to)),
                ('cultural_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cp_api.culturalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254, null=True)),
                ('note', models.CharField(max_length=254, null=True)),
                ('cultural_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='cp_api.culturalproperty')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
        migrations.AddField(
            model_name='culturalproperty',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cultural_properties', to='cp_api.tag'),
        ),
    ]
