# Generated by Django 5.1.4 on 2025-12-25 09:12

import cp_api.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_api', '0002_add_created_by_and_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'verbose_name': '画像', 'verbose_name_plural': '画像'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='address',
            field=models.CharField(max_length=254, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=6668, verbose_name='ジオメトリ'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name',
            field=models.CharField(max_length=254, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_en',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='英語名'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_gener',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='一般名称'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='name_kana',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='ふりがな'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='note',
            field=models.CharField(blank=True, max_length=4094, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='place_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='場所名'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cultural_properties', to='cp_api.tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='type',
            field=models.CharField(max_length=254, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='culturalproperty',
            name='url',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='参考URL'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='cultural_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cp_api.culturalproperty', verbose_name='文化財'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=cp_api.models.upload_to, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='note',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=254, verbose_name='URL'),
        ),
    ]
